"""
Exercise to muscle group mapping module.
This provides a direct, hardcoded mapping from exercise names to muscle groups
instead of using regex pattern matching.
"""

# Complete mapping dictionary
EXERCISE_MUSCLE_MAP = {
    # Chest exercises
    "Bench Press": "Chest",
    "Incline Bench Press": "Chest",
    "Decline Bench Press": "Chest",
    "Dumbbell Bench Press": "Chest",
    "Incline Dumbbell Press": "Chest",
    "Decline Dumbbell Press": "Chest",
    "Dumbbell Fly": "Chest",
    "Incline Dumbbell Fly": "Chest",
    "Decline Dumbbell Fly": "Chest",
    "Cable Fly": "Chest",
    "High Cable Fly": "Chest",
    "Low Cable Fly": "Chest",
    "Chest Press Machine": "Chest",
    "Pec Deck": "Chest",
    "Push Up": "Chest",
    "Incline Push Up": "Chest",
    "Decline Push Up": "Chest",
    "Chest Dip": "Chest",
    "Svend Press": "Chest",
    "Landmine Press": "Chest",
    "Floor Press": "Chest",
    "Machine Fly": "Chest",
    "Smith Machine Bench Press": "Chest",
    "Weighted Push Up": "Chest",
    "Cable Crossover": "Chest",
    "Cable Iron Cross": "Chest",
    "Plate Press": "Chest",
    "Guillotine Press": "Chest",
    "Hex Press": "Chest",
    "One Arm Push Up": "Chest",
    "Deficit Push Up": "Chest",
    "Archer Push Up": "Chest",
    "Close-Grip Bench Press": "Chest",
    "Wide-Grip Bench Press": "Chest",
    "Reverse-Grip Bench Press": "Chest",
    
    # Back exercises
    "Deadlift": "Back",
    "Barbell Row": "Back",
    "Dumbbell Row": "Back",
    "Pendlay Row": "Back",
    "T-Bar Row": "Back",
    "Seated Cable Row": "Back",
    "Machine Row": "Back",
    "Pull Up": "Back",
    "Chin Up": "Back",
    "Neutral Grip Pull Up": "Back",
    "Lat Pulldown": "Back",
    "Close Grip Lat Pulldown": "Back",
    "Wide Grip Lat Pulldown": "Back",
    "V-Bar Pulldown": "Back",
    "Straight Arm Pulldown": "Back",
    "Face Pull": "Back",
    "Meadows Row": "Back",
    "Chest Supported Row": "Back",
    "Chest Supported Dumbbell Row": "Back",
    "Bent Over Row": "Back",
    "Inverted Row": "Back",
    "Seal Row": "Back",
    "Cable Row": "Back",
    "Back Extension": "Back",
    "Good Morning": "Back",
    "Rack Pull": "Back",
    "Block Pull": "Back",
    "Deficit Deadlift": "Back",
    "Romanian Deadlift": "Back",
    "Stiff Leg Deadlift": "Back",
    "Snatch Grip Deadlift": "Back",
    "Sumo Deadlift": "Back",
    "Trap Bar Deadlift": "Back",
    "Landmine Row": "Back",
    "Band Pull Apart": "Back",
    "Reverse Fly": "Back",
    "Bent Over Rear Delt Raise": "Back",
    "Dumbbell Pullover": "Back",
    "Cable Pullover": "Back",
    "Renegade Row": "Back",
    "Seated Row": "Back",
    "Kroc Row": "Back",
    "Australian Pull Up": "Back",
    "One Arm Row": "Back",
    "Assisted Pull Up": "Back",
    "Superman": "Back",
    "Hyperextension": "Back",
    "Reverse Hyperextension": "Back",
    "Shrug": "Back",
    "Barbell Shrug": "Back",
    "Dumbbell Shrug": "Back",
    "Cable Shrug": "Back",
    "Machine Shrug": "Back",
    
    # Shoulder exercises
    "Overhead Press": "Shoulders",
    "Military Press": "Shoulders",
    "Seated Overhead Press": "Shoulders",
    "Standing Overhead Press": "Shoulders",
    "Dumbbell Shoulder Press": "Shoulders",
    "Arnold Press": "Shoulders",
    "Push Press": "Shoulders",
    "Machine Shoulder Press": "Shoulders",
    "Lateral Raise": "Shoulders",
    "Cable Lateral Raise": "Shoulders",
    "Front Raise": "Shoulders",
    "Cable Front Raise": "Shoulders",
    "Upright Row": "Shoulders",
    "Cable Upright Row": "Shoulders",
    "Bent Over Lateral Raise": "Shoulders",
    "Cable Reverse Fly": "Shoulders",
    "Rear Delt Machine": "Shoulders",
    "Reverse Pec Deck": "Shoulders",
    "Handstand Push Up": "Shoulders",
    "Pike Push Up": "Shoulders",
    "Barbell Face Pull": "Shoulders",
    "Cable Face Pull": "Shoulders",
    "Landmine Lateral Raise": "Shoulders",
    "Landmine Press": "Shoulders",
    "Bradford Press": "Shoulders",
    "Cuban Press": "Shoulders",
    "Dumbbell Complex": "Shoulders",
    "Lateral Raise Machine": "Shoulders",
    "YTW Raises": "Shoulders",
    
    # Arms (Biceps) exercises
    "Bicep Curl": "Arms",
    "Barbell Curl": "Arms",
    "Dumbbell Curl": "Arms",
    "Alternating Dumbbell Curl": "Arms",
    "Hammer Curl": "Arms",
    "Incline Dumbbell Curl": "Arms",
    "Spider Curl": "Arms",
    "Preacher Curl": "Arms",
    "Cable Curl": "Arms",
    "Concentration Curl": "Arms",
    "EZ Bar Curl": "Arms",
    "Reverse Curl": "Arms",
    "Zottman Curl": "Arms",
    "21s": "Arms",
    "Chin Up": "Arms",
    "Machine Curl": "Arms",
    "Resistance Band Curl": "Arms",
    "Cross Body Curl": "Arms",
    "Scott Curl": "Arms",
    "Rope Hammer Curl": "Arms",
    "Drag Curl": "Arms",
    "Bayesian Curl": "Arms",
    
    # Arms (Triceps) exercises
    "Tricep Extension": "Arms",
    "Tricep Pushdown": "Arms",
    "Rope Pushdown": "Arms",
    "V-Bar Pushdown": "Arms",
    "Overhead Tricep Extension": "Arms",
    "Skull Crusher": "Arms",
    "Close Grip Bench Press": "Arms",
    "Diamond Push Up": "Arms",
    "Dip": "Arms",
    "Tricep Kickback": "Arms",
    "JM Press": "Arms",
    "Tate Press": "Arms",
    "Board Press": "Arms",
    "Rolling Tricep Extension": "Arms",
    "Cable Overhead Tricep Extension": "Arms",
    "One Arm Overhead Extension": "Arms",
    "Machine Tricep Extension": "Arms",
    "Cable Tricep Extension": "Arms",
    "French Press": "Arms",
    "One Arm Pushdown": "Arms",
    "Bench Dip": "Arms",
    
    # Leg exercises
    "Squat": "Legs",
    "Back Squat": "Legs",
    "Front Squat": "Legs",
    "Hack Squat": "Legs",
    "Goblet Squat": "Legs",
    "Bulgarian Split Squat": "Legs",
    "Lunge": "Legs",
    "Walking Lunge": "Legs",
    "Reverse Lunge": "Legs",
    "Lateral Lunge": "Legs",
    "Step Up": "Legs",
    "Box Jump": "Legs",
    "Leg Press": "Legs",
    "Leg Extension": "Legs",
    "Leg Curl": "Legs",
    "Seated Leg Curl": "Legs",
    "Lying Leg Curl": "Legs",
    "Standing Calf Raise": "Legs",
    "Seated Calf Raise": "Legs",
    "Single Leg Deadlift": "Legs",
    "Hip Thrust": "Legs",
    "Glute Bridge": "Legs",
    "Single Leg Glute Bridge": "Legs",
    "Pistol Squat": "Legs",
    "Sissy Squat": "Legs",
    "Wall Sit": "Legs",
    "Smith Machine Squat": "Legs",
    "Belt Squat": "Legs",
    "Jefferson Squat": "Legs",
    "Zercher Squat": "Legs",
    "Overhead Squat": "Legs",
    "Bodyweight Squat": "Legs",
    "Jump Squat": "Legs",
    "Split Squat": "Legs",
    "Hack Squat Machine": "Legs",
    "Donkey Calf Raise": "Legs",
    "Machine Calf Raise": "Legs",
    "Sled Push": "Legs",
    "Leg Adduction": "Legs",
    "Leg Abduction": "Legs",
    "Cable Pull Through": "Legs",
    "Glute Kickback": "Legs",
    "Reverse Hyperextension": "Legs",
    "Nordic Curl": "Legs",
    "Kneeling Squat": "Legs",
    "Landmine Squat": "Legs",
    "Squat Jump": "Legs",
    "Box Squat": "Legs",
    "Cossack Squat": "Legs",
    "Barbell Glute Bridge": "Legs",
    "Smith Machine Calf Raise": "Legs",
    
    # Core exercises
    "Plank": "Core",
    "Side Plank": "Core",
    "Crunch": "Core",
    "Sit Up": "Core",
    "Russian Twist": "Core",
    "Leg Raise": "Core",
    "Hanging Leg Raise": "Core",
    "Cable Crunch": "Core",
    "Ab Wheel Rollout": "Core",
    "Mountain Climber": "Core",
    "V-Up": "Core",
    "Hollow Hold": "Core",
    "Dragon Flag": "Core",
    "Hanging Knee Raise": "Core",
    "Bicycle Crunch": "Core",
    "Dead Bug": "Core",
    "Bird Dog": "Core",
    "Wood Chopper": "Core",
    "Reverse Crunch": "Core",
    "Decline Sit Up": "Core",
    "Cable Wood Chopper": "Core",
    "Cable Twist": "Core",
    "Medicine Ball Slam": "Core",
    "Oblique Crunch": "Core",
    "Plank Variations": "Core",
    "L-Sit": "Core",
    "Windshield Wiper": "Core",
    "Toes to Bar": "Core",
    "Medicine Ball Throw": "Core",
    "Pallof Press": "Core",
    "Weighted Plank": "Core",
    "Weighted Crunch": "Core",
    "Suitcase Carry": "Core",
    "Farmer's Walk": "Core",
    "Stomach Vacuum": "Core",
    "Side Bend": "Core",
    "Ab Machine Crunch": "Core",
    
    # Olympic lifting
    "Clean": "Olympic",
    "Power Clean": "Olympic",
    "Hang Clean": "Olympic",
    "Clean and Jerk": "Olympic",
    "Snatch": "Olympic",
    "Power Snatch": "Olympic",
    "Hang Snatch": "Olympic",
    "Clean Pull": "Olympic",
    "Snatch Pull": "Olympic",
    "Push Press": "Olympic",
    "Push Jerk": "Olympic",
    "Split Jerk": "Olympic",
    "High Pull": "Olympic",
    "Muscle Snatch": "Olympic",
    "Muscle Clean": "Olympic",
    "Hang Power Clean": "Olympic",
    "Hang Power Snatch": "Olympic",
    "Clean High Pull": "Olympic",
    "Snatch Balance": "Olympic",
    "Overhead Squat": "Olympic",
    "Barbell Thruster": "Olympic",
    
    # Cardio exercises
    "Running": "Cardio",
    "Jogging": "Cardio",
    "Sprint": "Cardio",
    "Cycling": "Cardio",
    "Stationary Bike": "Cardio",
    "Elliptical": "Cardio",
    "Jump Rope": "Cardio",
    "Battle Ropes": "Cardio",
    "Swimming": "Cardio",
    "Rowing": "Cardio",
    "Walking": "Cardio",
    "Stair Climber": "Cardio",
    "Jumping Jack": "Cardio",
    "Burpee": "Cardio",
    "Treadmill": "Cardio",
    "HIIT": "Cardio",
    "Circuit Training": "Cardio",
    "Hill Sprint": "Cardio",
    "Ski Erg": "Cardio",
    "Assault Bike": "Cardio",
    "Box Jump": "Cardio",
    "Sled Push": "Cardio",
    "Sled Pull": "Cardio",
    "Prowler Push": "Cardio",
    "StairMaster": "Cardio",
    "Jacob's Ladder": "Cardio",
    "VersoClimber": "Cardio",
    "Interval Training": "Cardio",
    "Airdyne Bike": "Cardio",
    
    # Functional/Compound Movements
    "Turkish Get Up": "Compound",
    "Kettlebell Swing": "Compound",
    "Medicine Ball Throw": "Compound",
    "Thruster": "Compound",
    "Farmer's Carry": "Compound",
    "Trap Bar Carry": "Compound",
    "Sled Drag": "Compound",
    "Tire Flip": "Compound",
    "Battle Rope Exercise": "Compound",
    "Man Maker": "Compound",
    "Clean and Press": "Compound",
    "Sandbag Carry": "Compound",
    "Sandbag Clean": "Compound",
    "Log Press": "Compound",
    "Single Arm Dumbbell Snatch": "Compound",
    "Kettlebell Snatch": "Compound",
    "Kettlebell Clean": "Compound",
    "Medicine Ball Clean": "Compound"
}

def get_muscle_group(exercise_name):
    """
    Get the muscle group for a given exercise name
    
    Parameters:
    -----------
    exercise_name : str
        Name of the exercise
        
    Returns:
    --------
    str
        Muscle group name or 'Other' if not found
    """
    # First try direct lookup
    if exercise_name in EXERCISE_MUSCLE_MAP:
        return EXERCISE_MUSCLE_MAP[exercise_name]
    
    # Then try case-insensitive and partial matching
    exercise_lower = exercise_name.lower()
    for name, group in EXERCISE_MUSCLE_MAP.items():
        if name.lower() in exercise_lower or exercise_lower in name.lower():
            return group
    
    # Finally, try to find any partial match
    for name, group in EXERCISE_MUSCLE_MAP.items():
        if any(word.lower() in exercise_lower for word in name.lower().split()):
            return group
    
    # Return 'Other' if no match found
    return "Other"